# Welcome to Jekyll!
#

# Site settings
title: Shane Mileham
description: |
  Lifestyle Engineer |
  Athlete |
  Coach
owner: Shane Mileham LLC
first_published: 2014 # if migrating another site, the year of your first publish
email: shane.mileham@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "shanemileham.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/shanemileham
  linkedin-square: https://linkedin.com/in/shanemileham
  facebook-official: https://facebook.com/shanemileham
  #google-plus-square: https://plus.google.com/u/0/+shanemileham
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
