# Welcome to Jekyll!
#

# Site settings
title: Shane Mileham
description: |
  Entrepreneur |
  Lifestyle Engineer |
  Athlete
owner: Shane Mileham
first_published: 2014 # if migrating another site, the year of your first publish
email: shane.mileham@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "shanemileham.com" # the base hostname & protocol for your site
social:
  facebook-official: https://facebook.com/shanemileham
  linkedin-square: https://linkedin.com/in/shanemileham
  instagram: https://www.instagram.com/shanemileham/
  # angellist: https://angel.co/shanemileham
  github: https://github.com/shanemileham
  #twitter: https://twitter.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+shanemileham
  #email: /contact/
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# OCTOPRESS
# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft


# Defaults (https://jekyllrb.com/docs/configuration/#front-matter-defaults)
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# CUSTOM
layout: default
# Define Collections
collections:
  kb:
    output: true
    permalink: /kb/:path/
